### ISSUE TITLE
`match` just ignores you if there's no match...?

### ISSUE THREAD

**Issue by TheBizzle** [qiemem/ControlFlowExtension#1]
I typed `cf:match "derp" []` into the Command Center, and my code was entirely ignored.  I predict this leading to many subtle bugs for people.

**Comment by qiemem** [comment]
Right... That's intentional. If no cases match, no case is run. What would you expect to happen? Documentation should definitely clarify this though.

`cf:matching` on the other hand should error since it must return a value.

**Comment by TheBizzle** [comment]
I would expect an error.

**Comment by qiemem** [comment]
I view this as analogous to an `if` with a false condition, or a `switch` with no match. This is not analogous to Scala's `match` (despite the name) since there's no return.

Like I said, the reporter version should definitely error in this case.

**Comment by qiemem** [comment]
Hmm, as I think about it, though, you might be right. The primitive name certainly suggests that a match should be made. Requiring an explicit (blank) else to do nothing on no match is probably better. 

Do you think `cf:when` should also error? In that case, the primitive name is less suggestive, and it doesn't

**Comment by qiemem** [comment]
Hmm, as I think about it, though, you might be right. The primitive name certainly suggests that a match should be made. Requiring an explicit (blank) else to do nothing on no match is probably better. 

Do you think `cf:when` should also error? In that case, the primitive name is less suggestive, and intuitively, not erroring seems less bad, but consistency is important.

**Comment by qiemem** [comment]
Didn't mean to close.

**Comment by TheBizzle** [comment]
Personally, I would expect `select`, `when`, `match`, and `matching` to all error if no matching cases were found.  My logic is that the reason you reach for these primitives is that you have many things that you're trying to match on.  If you don't, you use `if`.

When you're trying to handle many cases, the odds of making an error and accidentally not covering a case that you thought you had covered go way up.  And the likelihood that you have a bunch of special things that you want to do in particular cases, but that there is also a "fallthrough" case where you want to do nothing are fairly low.  That is, if you're matching on a bunch of stuff, you are generally looking to do _something_ in _all_ cases, and just trying to figure out which something to do.  There are advantages and disadvantages to implicit fallthrough, but erroring seems to me to be the better solution.

In the case of wanting an implicit fallthrough and these primitives being designed to throw errors, the consequence is that you got an error, you're told exactly where it's coming from, and you have to explicitly add an `else []` (and the error message can even suggest this).  In the case where you made an error in writing your cases and these primitives **don't** throw errors on fallthrough, you then have a program that is not doing what you wanted and is giving you no sign of what went wrong or where.

**Comment by qiemem** [comment]
I'm convinced. Explicit-better-than-implicit, etc etc. I included basic "check out `cf:else`" messages in the errors.
