### ISSUE TITLE
cf:matching doesn't give syntax error but fails on runtime if you put match-var after instead of before

### ISSUE THREAD

**Issue by arthurhjorth** [qiemem/ControlFlowExtension#2]
The correct syntax for `cf:matching` is

```
let x <som-var> cf:matching list-of-cases

```

However, if you write

```
let x cf:matching <some-var> list-of-cases
```

the syntax checker accepts it, but it messes up during runtime and gives an error message about an anonymous procedure in the next statement.

**Comment by qiemem** [comment]
old syntax
