### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by mrerrormessage** [qiemem/ControlFlowExtension#4]
One of our users writes:

> Some suggestions to improve the manual regarding the Control Flow 
> extension:
>
> 1) The text uses CF, but never says it stands for Control Flow.
>
> 2)  In the section labeled "Cases" the text gives an example of how
> this could be done without using CF.  However, it uses "task" in the 
> code example.  Since task is no longer a primitive under v 6.0, the code 
> will generate an error.
>
> 3)  The word "task" is also used in cf:when,  cf:select, and cf:case. 
> Since "task" is not a primitive and has been replaced elsewhere by 
> anonymous procedures, it is a bit confusing to use that word here.
>
> Maybe just calling them command blocks and reporter blocks in the 
> explanation of those primitives would suffice.

**Comment by daimpi** [comment]
In the section "cf:match" the example given reads:

`ask patch 0 0 [ set color red ]` […]

which would give the Error: 
> this code can't be run by a patch

it should probably read `ask patch 0 0 [ set pcolor red ]` 

and the output should probably not read:
> The above code will print out The center patch is green! […]

but rather

> The above code will print out The center patch is red! […]

**Comment by qiemem** [comment]
This is no longer applicable with the new syntax.
