### ISSUE TITLE
Multiple conditions in one if statement in Netlogo

### ISSUE THREAD

**Issue by ranamajid007** [qiemem/ControlFlowExtension#5]
Hi everyone,

I want to write 'and' conditions within one if statement in Netlogo. For example

if( tempx0 = tempx1 and tempy0 = tempy1)..........like this.

condition 1 = tempx0 =tempx1
condition 2 = tempy0 = tempy1

I mean if both the conditions satisfy then the command should execute. Can some one help me how to do that in Netlogo?

Thanks

**Comment by qiemem** [comment]
Hi,

Just to be clear, this page is for post bug reports about the NetLogo cf extension. Questions about NetLogo programming are better asked on the [netlogo user group](https://groups.yahoo.com/neo/groups/netlogo-users/info) or [stackoverflow](https://stackoverflow.com/questions/tagged/netlogo).

That said, I'm happy to answer your question. You've actually already written the correct answer! Just put `and` between the conditions.

```
if tempx0 = tempx1 and tempy0 = tempy1 [
  ;; do stuff
]
``
